### ISSUE TITLE
Add new plugin API

### ISSUE THREAD

**Issue by egtann** [itsabot/itsabot#167]
There’s going to be a new, much simpler plugin API. You can see an example [here](https://gist.github.com/egtann/8dc174ab9fdc776e4fabc0356d15d772). Notably, Command+Object triggers will now be assembled automatically from example sentences. Read the comments in the linked example—it’s really powerful. The current API will be deprecated but not removed until v1.0.

This should lay the groundwork for a visual plugin builder with a drag-and-drop interface.

**Comment by joeblew99** [comment]
The visual plugin builder sounds very interesting.

I am curious on the architecture proposed for this.
I have built similar things using polymer web components.

If you have any example code / specs let me know.
I could help.
