### ISSUE TITLE
Plugins of other users can be published

### ISSUE THREAD

**Issue by egtann** [itsabot/itsabot#80]
I can publish a plugin on behalf of another user. This is not a desirable behavior.

To combat this, we'll add a required "Maintainer" key on `plugin.json` which must have the itsabot.org registered email you intend to publish plugins under. It's similar to how some services require DNS changes to demonstrate proof-of-ownership over a domain. Just like that, we'll require you to set a verifiable value in something that only you (or people to whom you give access) can control. Instead of DNS, it's your plugin.json.

This is susceptible to another attack, though, where I register on itsabot.org with an email that's not mine, but one that matches a known Maintainer email, so it'll allow falsely publishing a plugin under that email. To solve that, we'll have to implement email verification from itsabot.org to prove ownership over the email.

With these two steps, we can verify that you own the plugin you're publishing!

**Comment by egtann** [comment]
The plugins.json spec is changing. The key will be `Maintainers` (plural). It will have an array of names/emails in the following format:

```json
{
    "Maintainers": [
        "Evan <evan@itsabot.org>",
        "Jim Bean <jim@example.com>"
    ]
}
```

This enables multiple people to train a plugin.

**Comment by hhsnopek** [comment]
My thoughts on this are that if someone where to publish their plugin thru a service like github, gitlab, svn, etc - maintainers are able to track who can publish/commit what. Abot isn't consuming the code and hosting, or at least I'd hope not - but I would say that the user must verify their affiliation to their account the `X` service. This way only that user can publish their own work, like connection github so I can publish `github.com/hhsnopek/emoji-weather`, they'd both know that my user is connected to that account name.

**Comment by egtann** [comment]
Right. Confirming that the maintainer's email matches in `plugin.json` is a way to connect the account that's independent of any provider. If it can fetched via `go get`, then you can confirm your ownership over it.

Going a more traditional route to verify account ownership via OAuth would be provider-specific, and self-hosting code would effectively not even be an option because you'd need to build and run/maintain your own OAuth provider service.

Depending on the `Maintainer` in plugin.json skirts around all those problems.

**Comment by egtann** [comment]
All changes are in place except for the `Maintainer` requirement on publish. I'll get that in soon.

**Comment by GenaBitu** [comment]
What about gpg signatures on the plugins?

**Comment by egtann** [comment]
I don't see GPG adding much security. You already have to log in to itsabot.org, and verify ownership over both your email and the plugin. Plugins can't be modified except by:

1. Hacking your Github/BitBucket account or GPG keys.
2. Forking the plugin and publishing a new one under a different name.
