### ISSUE TITLE
Voice support

### ISSUE THREAD

**Issue by egtann** [itsabot/itsabot#94]
It'd be great to build an interface that enables communication from Abot via voice.

Whoever wants to tackle this would have to design an interface to communicate with arbitrary voice recognition APIs (Google, Nuance, etc.), then implement that interface in a driver for at least one of those.

To get started, take a look at one of the existing interfaces, such as the SMS interface. Then see how a driver integrates with it by implementing that SMS interface: Twilio driver.

**Comment by itsbalamurali** [comment]
you mean speech to text or text to speech?

**Comment by egtann** [comment]
Great point. We'll actually need both! It does no good to understand speech but not be able to respond in kind.

Any interface would have to ensure that drivers supported *both* speech to text and text to speech.

**Comment by egtann** [comment]
Ignore the removal of the `help wanted` label. Help is still wanted :)

**Comment by njaremko** [comment]
Google's speech API isn't public yet, so we'll have to wait on that. 

Side note: is this feature specific to desktop clients? Because most mobile interaction would be through text, which would use iOS/Android voice support.

**Comment by egtann** [comment]
Desktop and mobile in the case of an app. Think Siri more than Facebook M

**Comment by DaleWebb** [comment]
IBM Watson also have an API for speech-to-text and text-to-speech http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/speech-to-text.html

**Comment by jonathanpeterwu** [comment]
IBM Watson speech-to-text accuracy is so so. 

Bing Speech API is surprisingly a lot more accurate and fast - 

https://www.microsoft.com/cognitive-services/en-us/speech-api

**Comment by mpathy** [comment]
The Google Speech API is now also available and quite good:
https://cloud.google.com/speech/

Besides that, there are some other very interesting APIs, like the Natural Speech API for analyzing the text:
https://cloud.google.com/natural-language/

I would use those
